name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - stg
      - prd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Optional)
        run: |
          echo "Running tests..."
          # pytest 또는 다른 테스트 명령어를 추가 가능

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ github.ref_name }} environment"
          # 실제 배포 스크립트를 여기에 넣습니다.
